# Generated by Django 4.2 on 2023-05-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protect', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeCode',
        ),
    ]
